// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJXZekiuXMmr2x8WzkWB4kO3GLPWd_ko',
    appId: '1:769420746617:web:2efec4f3b22eba0542d9a8',
    messagingSenderId: '769420746617',
    projectId: 'patient-mangement-system',
    authDomain: 'patient-mangement-system.firebaseapp.com',
    databaseURL: 'https://patient-mangement-system-default-rtdb.firebaseio.com',
    storageBucket: 'patient-mangement-system.appspot.com',
    measurementId: 'G-Y7PX6ZW2QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRktA9ZYs4OKsQzEo2Yv-_ZSdmcWbsdw',
    appId: '1:769420746617:android:6df52856c134598842d9a8',
    messagingSenderId: '769420746617',
    projectId: 'patient-mangement-system',
    databaseURL: 'https://patient-mangement-system-default-rtdb.firebaseio.com',
    storageBucket: 'patient-mangement-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pXQIVaiKeIZ7TwVm-A5kJMU_je3SiF8',
    appId: '1:769420746617:ios:be532de468452c6842d9a8',
    messagingSenderId: '769420746617',
    projectId: 'patient-mangement-system',
    databaseURL: 'https://patient-mangement-system-default-rtdb.firebaseio.com',
    storageBucket: 'patient-mangement-system.appspot.com',
    iosClientId: '769420746617-a0nuleche9tjrt70j5ppqpn7cat2avkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0pXQIVaiKeIZ7TwVm-A5kJMU_je3SiF8',
    appId: '1:769420746617:ios:be532de468452c6842d9a8',
    messagingSenderId: '769420746617',
    projectId: 'patient-mangement-system',
    databaseURL: 'https://patient-mangement-system-default-rtdb.firebaseio.com',
    storageBucket: 'patient-mangement-system.appspot.com',
    iosClientId: '769420746617-a0nuleche9tjrt70j5ppqpn7cat2avkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ps',
  );
}
